### ISSUE TITLE
Doesn't work in Nuxt 3

### ISSUE THREAD

**Issue by mohsin** [danielroe/vue-bind-once#178]
**🐛 The bug**
This library fails to create a consistent value across server and client in Nuxt 3. I tried it using the README instructions you provided on a fresh project and it fails.

**🛠️ To reproduce**

1. Create a fresh nuxt app using `pnpm dlx nuxi init binding-test` and run `pnpm install` to get all dependencies.
2. Include this library `pnpm add vue-bind-once`.
3. Follow README instructions to add the input field to app.vue. Additionally, add value: id for convenience to see the value on the browser along with a console.log(id) on the setup script.
4. Open the app in the browser to see different IDs inside the console and input field--thus making this library unusable on Nuxt 3 projects.

[Live demo](https://creative-shortbread-64dbaf.netlify.app) and [Source code](https://github.com/mohsin/binding-test)

**🌈 Expected behaviour**
The client and server ID should be the same so the browser console and the input value should be the same.

**ℹ️ Additional context**
I tried manually creating a Nuxt 3 plugin `uniqId.js` in my Nuxt project with the following code:
```
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.directive('bind-once', {
    created: (el, binding) => {
      el.setAttribute('id', 'hello')
    },
    getSSRProps (binding) {
      if (!binding.value) return {}
      console.log(binding.value)
    }
  })
})
```
Ideally, if should set ID as hello and return hello in my terminal output during SSR too. But it does not (returns undefined). I'm thinking Nuxt 3 behaves differently so something is weird?

**Comment by danielroe** [comment]
This doesn't update your value within your `<script>` - instead, it ensures that there is no issue with hydrating the _rendered_ HTML.

So in your example it's working correctly when you look at the DOM:

<img width="493" alt="CleanShot 2023-05-07 at 16 07 50@2x" src="https://user-images.githubusercontent.com/28706372/236685796-c7013e6e-9ef1-45c4-9c6a-87cf7b5bc02f.png">
